### ISSUE TITLE
Be possible to run into a Web Runtime

### ISSUE THREAD

**Issue by Kikobeats** [grammyjs/grammY#113]
Hello,

I noted the library is using node-fetch as HTTP client:
https://github.com/grammyjs/grammY/blob/main/package.json#L28

If the library uses an isomorphic like [isomorphic-unfetch](https://www.npmjs.com/package/isomorphic-unfetch) instead, it will enable running the library in more places, like [Vercel Edge Functions](https://vercel.com/edge).

**Comment by KnorpelSenf** [comment]
You are only looking at the backport for Node.js. The library is not written for Node.js. It does not require `node-fetch` (unless you are using the Node.js backport).

**Comment by KnorpelSenf** [comment]
FYI you can already get a version that runs in modern browsers at https://get.grammy.dev/es6@v1.4.2.js but please follow #111 because that is still experimental.

**Comment by KnorpelSenf** [comment]
#116 is related, too
