### ISSUE TITLE
How api.sendDocument work ?

### ISSUE THREAD

**Issue by emmtte** [grammyjs/grammY#118]
Hi, with telegraf, it was possible to change the name of the file with:
````bot.telegram.sendDocument(chat_id, { source: `name.json`, filename: `other_name.json`}, [{ disable_notification: true }] );````
How to do this with grammyY, I only found this:
````bot.api.sendDocument(chat_id, new InputFile('name.json'))````

**Comment by KnorpelSenf** [comment]
You can pass two arguments to `InputFile`. The first one is the file path on disk, and the second one is an optional new filename:
```
new InputFile ("/path/to/file", "new-name.txt")
```

**Comment by KnorpelSenf** [comment]
This isn't mentioned in the docs, is it? It should be added.

**Comment by emmtte** [comment]
Thanks for the very fast help. I didn't found in documentation but I'm not an expert 
👍

**Comment by KnorpelSenf** [comment]
I will add it here: https://grammy.dev/guide/files.html#uploading-your-own-files
