### ISSUE TITLE
feat: Enumerate all sessions

### ISSUE THREAD

**Issue by KnorpelSenf** [grammyjs/grammY#131]
I'm thinking about allowing

```ts
for await (const data of ctx.session) {
  // handle session data of user
}
```

which would effectively allow you to enumerate all sessions.

This would be optional to implement for storage adapters. Hence, it is a non-breaking change. Storage adapters that do not support this will simply throw an error when this is attempted.

_Originally posted by @KnorpelSenf in https://github.com/grammyjs/grammY/issues/130#issuecomment-990478496_

**Comment by slavafomin** [comment]
Could you provide more details (rationale) regarding the use cases?

**Comment by KnorpelSenf** [comment]
People are regularly asking for ways to get all session data, especially newcomers who may not actually know too much about their storage solution. This would be a more convenient and more approachable way to do get all session data.

**Comment by slavafomin** [comment]
What are they are going to do with this data? I don't see any practical application for this feature at this point. Is there any specific use cases?

**Comment by KnorpelSenf** [comment]
That's a good question that I don't have the answer to

**Comment by slavafomin** [comment]
I think that we should always ask such questions before implementing anything. The final goal is to make apps development easier and we should look at the library from that point of view.

**Comment by KnorpelSenf** [comment]
I absolutely agree. I knew there was something wrong here, so I asked you to ask the right questions :D

Now that I think further about it, this solution also would not scale at all. Any bot with a significant number of users trivially isn't able to get all their data while handling a single update. Closing.

**Comment by u2x1** [comment]
Maybe sometimes there are scheduled jobs to run for some users, and when we restart the bot we need to enumerate all sessions and check if they have subscribed the service and initiate a new cron job for them?

**Comment by KnorpelSenf** [comment]
Iterating over millions of entries can take several hours, so it cannot be performed reliably library-side. We are going to achieve this at some point, but in the core lib and not without significant effort. The problem here isn't that there are no use cases. The problem is that it's very hard to get right.

**Comment by u2x1** [comment]
Could you please tell me is there any way I can just make a handy function to iterate my sessions? I think my bot will not reach a scale of millions, it's just my friends and me using it. I just need to recover the cron jobs when restarting the bot but not while running.

**Comment by KnorpelSenf** [comment]
You can just directly access the storage solution that you use under the hood (your database or whatever).
