### ISSUE TITLE
Bug: undefined and unspecified have different behavior

### ISSUE THREAD

**Issue by EdJoPaTo** [grammyjs/grammY#144]
I migrated yet another bot to grammy and found out that there is something fishy here.
I do not use transformers or something, its so far a plain Telegraf → grammY migration.

Technically `telegraf-inline-menu` → `grammy-inline-menu` is used which sets undefined to some properties instead of omitting them. I recreated the issue with plain grammY calls but haven't looked into it what exactly might cause this issue.

The goal is to send a photo without caption.

```typescript
await context.replyWithPhoto(media, {caption: undefined});
```

Ends up creating a photo message with a caption which is literally saying "undefined".

```typescript
await context.replyWithPhoto(media, {caption: undefined, parse_mode: undefined});
```

Fails with "Call to 'sendPhoto' failed! (400: Bad Request: unsupported parse_mode)"
Part of the error contains this, which indicated the error still thinks the `undefined` is `undefined` and not the string `"undefined"`:
```javascript
{
  method: 'sendPhoto',
  payload: {
    chat_id: 2956631,
    photo: 'attach://hyyujfn4azjcick6',
    caption: undefined,
    parse_mode: undefined
  },
  ok: false,
  error_code: 400,
  description: 'Bad Request: unsupported parse_mode',
  parameters: {}
}
```

I did not create a minimal bot to check these calls in a simple environment but as the bot is not that complex I dont think there are side effects to it currently. But I might be wrong here.

**Comment by KnorpelSenf** [comment]
These values should already get stripped for JSON requests. Can you confirm that this bug only reproduces when uploading own files, and that it doesn't reproduce when sending an image by file identifier or URL?

**Comment by EdJoPaTo** [comment]
Can confirm. Sending images via URL works fine, this only happens via InputFile.
