### ISSUE TITLE
Compatibility with Deno deploy

### ISSUE THREAD

**Issue by jokasimr** [grammyjs/grammY#15]
Hi, cool project!

I tried using grammY in a [Deno deploy](https://deno.com/deploy/docs) function and got the error 
`TypeError: cannot read property 'query' of undefined grammy Deno` in[ this line](https://github.com/grammyjs/grammY/blob/97a79f85b2ebc2e9ec626655e7c6b717238df695/deno/src/platform.ts#L14).

The line is `let res = await Deno.permissions.query(env)` and as I understand it the problem is that [Deno deploy does not expose the `Deno.permissions` API](https://deno.com/deploy/docs/runtime-api).

Not sure if this is something worth/possible doing anything about, but it would be very nice to be able to use this framework for deploying telegram bots on Deno deploy.

Thank you for the framework.

**Comment by KnorpelSenf** [comment]
Hi there, I understand your need to host on Deno Deploy, that would indeed be awesome. We talked about this a few weeks ago in the group chat, and already noticed this problem.

It would probably just be the right thing to remove the interactivity from grammY again, i.e. completely remove all references to `Deno.permission`. Instead, we just go ahead and access the env variables, catch an exception, and disable debug logs. In other words, we treat missing env access as no variable set.

I'd be happy to review your PR for this. If you don't know how to perform this change, or you don't have the time for it, then I can look into it myself at some point in the future.

**Comment by KnorpelSenf** [comment]
cc @trgwii

**Comment by trgwii** [comment]
I recommend removing all usage of the Deno.permissions API as Deno users can let the app ask for permissions with `deno run --prompt` now if they want, and the app needs no extra code to deal with this.

**Comment by KnorpelSenf** [comment]
@jokasimr thanks for reporting this bug btw! 
cc @all-contributors

Would not have been fixed if you had not brought up the topic again.

**Comment by KnorpelSenf** [comment]
@all-contributors add @jokasimr for bug
