### ISSUE TITLE
Grammy.dev 502 API reference

### ISSUE THREAD

**Issue by vinclou** [grammyjs/grammY#150]
## First of all thank you a lot for this tool! 
`There's a problem with the deployed website, you might already know about. `

If you go to grammy.dev and click API Reference - the link to `https://doc.deno.land/https://deno.land/x/grammy/mod.ts`
will be broken and show you 502 - `DEPLOYMENT_FAILED`. 

I'm not sure if it's on your end or Deno deploy. Yet, that would be nice to look into.

Thank you!

**Comment by KnorpelSenf** [comment]
That was probably a temporary issue. Please try again, it works for me.

**Comment by vinclou** [comment]
> That was probably a temporary issue. Please try again, it works for me. 

Indeed! It might be something wrong with deno.doc.land then, it's been pretty sluggish lately. 

Thank you.
