### ISSUE TITLE
ctx.answerCbQuery not a function

### ISSUE THREAD

**Issue by guttermouth99** [grammyjs/grammY#168]
I am currently refactoring my bot from telegraf to grammy. However, some functionality I cannot rebuild because I am missing the function answerCbQuery(). I am sending the following inline button which has a corresponding method for 'callback_query'.

My bot.on() is triggred and my code reaches inside the below if-statement but then cannot access the method returning (**TypeError: ctx.answerCbQuery is not a function**)

### Button Template
```
const buttons = [
      [
        {
          text: 'Click for callback query ',
          callback_data: 'test_button',
          hide: false
        }
]

await bot.api.sendPhoto(chatId,
      https://picsum.photos/1080/1080,
      {
        caption: 'test caption',
        parse_mode: 'markdown',
        reply_markup: {
          columns: 1,
          inline_keyboard: buttons
        }
      })
```

### bot.on listener
```
bot.on('callback_query', async (ctx, next) => { 
 if (ctx.callbackQuery.data.includes('test_')) {
  await ctx.answerCbQuery('test callback clicked', true)
 } else {
  return next()
 }
}
```

I have tried various solutions from ranging **ctx.api.answerCbQuery('...')** **to bot.api.answerCbQuery('...')**. However, I cannot access this method. Which was possible in my previous setup without a problem. Any help appreciated.

**Comment by KnorpelSenf** [comment]
grammY uses the same names as the official Telegram Bot API. The method is called `anawerCallbackQuery` (Telegraf just renamed it.)

**Comment by guttermouth99** [comment]
Thanks! I guess I tested so many ways of this method that I totally missed out on this one!

My solution:

`     bot.api.answerCallbackQuery(ctx.callbackQuery.id, { text: 'hey answer', show_alert: true })`

**Comment by roj1512** [comment]
@guttermouth99 You can use TypeScript to ruin the chances of facing problems similar to this in the future.

**Comment by KnorpelSenf** [comment]
> 

That works. Also consider using `ctx.answerCallbackQuery`.
