### ISSUE TITLE
bug: wrong ctx type in composer.command with exactOptionalPropertyTypes enabled

### ISSUE THREAD

**Issue by yrzam** [grammyjs/grammY#180]
ctx has type 'never' in composer.command when I set exactOptionalPropertyTypes in tsconfig to true.

```typescript
const cmp = new Composer();
cmp.command('start', (ctx) => ctx.reply('test'));
```
> Property 'reply' does not exist on type 'never'

[tsconfig](https://github.com/grammyjs/grammY/files/8451440/tsconfig.txt)

**Comment by KnorpelSenf** [comment]
Thanks again for reporting. @all-contributors add @yrzam for bug.

**Comment by KnightNiwrem** [comment]
@KnorpelSenf @yrzam It seems like this might no longer be an issue for later versions of grammY/typescript. At least, with the given snippet and tsconfig, there are no tsc build warnings or errors.

**Comment by KnorpelSenf** [comment]
Fascinating, I procrastinated looking into this any further. I remember being able to reproduce it back then.

I'll close this. Feel free to comment or reopen if this is still an issue.
