### ISSUE TITLE
How to delete bot's messages?

### ISSUE THREAD

**Issue by habdenscrimen** [grammyjs/grammY#209]
I want to delete the old bot's messages to provide a better UX and "feeling of real dialog." This can be achieved by doing something like this:
```ts
const message = await ctx.reply('message here')

// wait 1 second
await new Promise((resolve) => setTimeout(resolve, 1000))

await ctx.api.deleteMessage(ctx.chat.id, message.message_id)
```

And even more, I can save the message ID to the session and then, at some moment, delete all messages from this list.

```ts
// get session
const session = await ctx.session

// send message1 (will be deleted) and add its ID to session
const message1 = await ctx.reply(`1st message`)
session.messageIDsToDelete.push(message1.message_id)

// send message2 (will be deleted) and add its ID to session
const message2 = await ctx.reply(`2nd message`)
session.messageIDsToDelete.push(message2.message_id)

// delete bot's messages before sending 3rd one
await Promise.all(
  session.messageIDsToDelete.map((messageID) =>
    ctx.api.deleteMessage(ctx.chat.id, messageID),
  ),
)

// send 3rd message
await ctx.reply(`3rd message`)
```

But it's not convenient to add message IDs to the list every time and then delete them manually (I have several routers, and some messages need to be deleted and some not). So I think about adding message IDs to the list and deleting messages from that list using middleware. Like this (not real code):
```ts
await ctx.reply(`1st message`, { toDelete: true })

await ctx.reply(`2nd message`, { toDelete: true })

await ctx.reply(`3rd message`, { deletePrevious: true })
```

So my questions are:
1. Is there existing ways for deleting the bot's messages?
2. Can I pass custom metadata to messages (like `toDelete` and `deletePrevious` from my example above)?
3. How can I catch the bot's messages using middleware? It seems like I can catch only users' messages.

**Comment by EdJoPaTo** [comment]
I personally have not used them yet but I assume they should be helpful for you: <https://grammy.dev/advanced/transformers.html>

Their basic idea is to provide something like the middleware but for outgoing messages. That sounds like what you want to accomplish. (To the grammY experts there, correct me if I am wrong :innocent:)

**Comment by KnorpelSenf** [comment]
1. Calling deleteMessage is the only way to delete a message. You'll need to call it once per message, just like your example shows.
2. You can change the API surface that grammY uses however you want. This is a bit tricky to do right with type safety, because you have to be skilled in TS, but there are several plugins that do this. In pure JS, your not-real-code example will be a valid way to use the feature, given you implemented the internal logic correctly which maps these properties back to deleteMessage calls.
3. You can use transformer functions for that. You'll need to play around with your custom context flavour to change the type signature of `reply` to what you want to have.

**Comment by habdenscrimen** [comment]
Thank you!
One more pitfall. I need access to the message ID in the transformer, but I can't get it in `payload`. So I can pass  `{ toDelete: true }` to `reply` and get it, but I can't pass the message ID because `message` doesn't exist yet.

```ts
// send message with custom payload
await ctx.reply(`my message`, { toDelete: true })

// transformer
bot.api.config.use((prev, method, payload, signal) => {
  // payload.toDelete === true
  // payload.text === 'my message'

  // But I need message ID here

  return prev(method, payload, signal)
})
```

**Comment by KnorpelSenf** [comment]
```ts
const response = await prev(method, payload, signal)
if (response.ok && "message_id" in response.result.message_id) {
  const id = response.result.message_id
  // Store id for later deletion
}
return response
```

**Comment by habdenscrimen** [comment]
Ah, got it :)
Thank you!

**Comment by KnorpelSenf** [comment]
You're welcome :)

I'll close this, feel free to comment or reopen if you have further questions :)
