### ISSUE TITLE
feat: Add `bot.chosenInlineResult`

### ISSUE THREAD

**Issue by askador** [grammyjs/grammY#215]
this registers middleware for [chosen_inline_result](https://core.telegram.org/bots/api#choseninlineresult) that will be executed for a certain result_id(s)  

```ts
bot.chosenInlineResult('resultId', async ctx => {...})
```

**Comment by tusharwebd** [comment]
Hi! I would like to work on this request. This is going to be the first open-source issue I'll work on. Please let me know if you can assign this task to me. Thanks!

**Comment by KnorpelSenf** [comment]
> Hi! I would like to work on this request. This is going to be the first open-source issue I'll work on. Please let me know if you can assign this task to me. Thanks!

Great to hear, looking forward to your contribution!

**Comment by KnorpelSenf** [comment]
Feel free to ask any questions if you get stuck or need help, either here on GitHub or in https://t.me/grammyjs :)

**Comment by KnorpelSenf** [comment]
@tusharwebd did you find any time to look into this yet?

**Comment by tusharwebd** [comment]
> @tusharwebd did you find any time to look into this yet?

Hi! Sorry for the delay. I've started working on this and will have an update on this by Monday?!

**Comment by KnorpelSenf** [comment]
No worries, there's no hurry. This change is supposed to land in 1.11 but we have the 1.10 release before that anyway, so please take your time. I was just curious if you were still interested in working on this :)

**Comment by KnorpelSenf** [comment]
The new update changed a lot about the internals that are relevant for this. Let me know if you have any questions about how to work on this :)

**Comment by KnorpelSenf** [comment]
@tusharwebd I assume you no longer feel like working on this, how is that? :(

**Comment by MrVSiK** [comment]
Hi! Is anyone working on this feature?

**Comment by KnorpelSenf** [comment]
It does not seem like that. @MrVSiK it would be great if you can take over, are you interested in this?

**Comment by MrVSiK** [comment]
Yes, I'd like to give it a shot

**Comment by MrVSiK** [comment]
Yes, I'd like to give it a shot
