### ISSUE TITLE
Bot is not starting on first "Start" command only after pressing "Restart"

### ISSUE THREAD

**Issue by guttermouth99** [grammyjs/grammY#233]
I am running grammy 1.9, express.js and Node 16.13. I recently started experiencing an issue that my bot does not start when pressing the initial "Start" button inside telegram. After pressing the Start button the "Restart" button appears. If I press this button again the bot actually listens to the start command. So I basically always need to type in /start twice to get my first response.
![Screenshot 2022-07-01 at 14 28 47](https://user-images.githubusercontent.com/78426376/176894802-8c25ca79-4ad8-4727-8b21-84cb03cb50e9.png)
![Screenshot 2022-07-01 at 14 33 53](https://user-images.githubusercontent.com/78426376/176895308-785f7806-1ace-49df-9fd1-c329e9932b9b.png)

I have completely isolated the problem by starting a simple express server from scratch and using the default configuration described in the grammy documentation. The problem persists and lets me wonder if this might be related to a recent telegram update (https://core.telegram.org/bots/api#june-20-2022). 

I am pretty much clueless where this could come from. Is anyone else experiencing and issue like this?

Thanks for your help!

**Comment by KnorpelSenf** [comment]
Can you share the code?

Also, bots can't actually make clients display restart buttons. This is something that happens internally in Telegram, and that bots have no control over.

**Comment by guttermouth99** [comment]
I am just running this code. For me it looks like its a telegram issue. I created a new Bot and it worked perfectly. However using another bot it does not work. Its also seems to be user specific. I talked to some friends and it seemed to work for them while it was not working for me. Any idea, what this could be related to? As you said the "Restart" is something telegram does. 

```
const bot = new Bot(xxx)

bot.command("start", (ctx) => ctx.reply("I'm running on Heroku using long polling!"));

const runner = run(bot);

// Stopping the bot when the Node process
// is about to be terminated
const stopRunner = () => runner.isRunning() && runner.stop();
process.once("SIGINT", stopRunner);
process.once("SIGTERM", stopRunner);
```

**Comment by KnorpelSenf** [comment]
This issue is unrelated to grammY.

There is likely a bug in Telegram. Can you narrow down which clients were used to reproduce the problem, and which versions of it?

Btw `runner.isRunning()` only checks if your bot is ruining but doesn't stop it. Did you mean `runner.stop()`?

**Comment by guttermouth99** [comment]
Hey,

so I actually just use the bot.start() instead of the runner. I am using the 8.8.1.232774 Stable Mac Version of Telegram Desktop Client.  The following is my new testing code. I just run it via node bot.js. Same problem bot only starts to react after pressing Restart and not initial Start.

```

//bot.js
const { Bot } = require("grammy")

const bot = new Bot('xxx')

bot.command("start",(ctx) => ctx.reply("This is my test message"))
bot.start()
```

**Comment by guttermouth99** [comment]
I just created a complete new Bot via BotFather and the newly created bot works just fine with the code.

**Comment by guttermouth99** [comment]
> Hey,
> 
> so I actually just use the bot.start() instead of the runner. I am using the 8.8.1.232774 Stable Mac Version of Telegram Desktop Client. The following is my new testing code. I just run it via node bot.js. Same problem bot only starts to react after pressing Restart and not initial Start.
> 
> ```
> 
> //bot.js
> const { Bot } = require("grammy")
> 
> const bot = new Bot('xxx')
> 
> bot.command("start",(ctx) => ctx.reply("This is my test message"))
> bot.start()
> ```


I just created a new Bot via BotFather and the newly created bot works just fine. This only seems to be related to older bots.

**Comment by KnorpelSenf** [comment]
If you know how other people can reproduce this reliably, you can open a bug a report at https://bugs.telegram.org. I will close this issue as it has nothing to do with grammY.
