### ISSUE TITLE
feat: Add folder structure and automatically register the listeners, commands, and callback queries

### ISSUE THREAD

**Issue by ppabcd** [grammyjs/grammY#234]
I have an idea that grammy has a folder structure for each listener, command, and callback query and automatically registers all of them. The example structure is like below...
```
project
├── index.ts
├── commands
│   ├── help-command.ts
│   ├── start-command.ts
├── listeners
│   ├── btn-show-listener.ts
├── callbacks
│   ├── sample-callback.ts
```
and in example inside of help-command.ts it will like this.
```typescript
export class HelpCommand extends Command{
    constructor() {
        // Grammy will automatically register the command help and h
        super(['help', 'h'], CommandType.ANY)
        // Add on middleware when the developer wants to check the data before call execute.
        this.middleware = [
            new CheckUserMiddleware()
        ]
    }
    execute(ctx: Context){
        // run the code here for general (private and group)
    }
    executePrivate(ctx: Context){
        // run the code if private and group has different code
    }
    executeGroup(ctx: Context){
        // run the code if group and private has different code
    }
}
```
The first parameter in the constructor is the command that the user call to the bot and the second one is the type of command, here also can add more option related to the command. In the second parameter, the type is starting from any, private, and group. The command also can use specific middleware that is registered in the constructor before calling execute method.
That's all my suggestions, Thank you...

**Comment by KnorpelSenf** [comment]
This is not going to be added to the grammY core library. The focus there is to make the Bot API accessible, but your suggestion concerns itself with code organisation. Instead, this would go into a plugin.

Have you considered using a plugin such as the integration with NestJS to be able to use this pattern?

If you are not happy with the way how NestJS does it, the right way forward with this idea would be to create a new, separate plugin. This would allow people to write the code you suggested.

Feel free to comment on #110 and start working on it. Once you have something to show off, leave a link here or in #110 or in https://t.me/grammyjs. With sufficient demand, you can become the plugin maintainer of this plugin and have it published under @grammyjs on GitHub and npm. Hence, I will close this issue now.
