### ISSUE TITLE
bug: Type 'MyContext' does not satisfy the constraint 'Context'. Types of property 'has' are incompatible. 

### ISSUE THREAD

**Issue by adnanlah** [grammyjs/grammY#263]
Hello!

I get the error `Type 'MyContext' does not satisfy the constraint 'Context'. Types of property 'has' are incompatible. ` when I try to create a new Bot. The problem only happens with version 1.10 of Grammy and not with the 1.9.2 version.

```ts
type MyContext = HydrateFlavor<Context> & SessionFlavor<SessionData>
type MyApi = HydrateApiFlavor<Api>

export const bot = new Bot<MyContext, MyApi>(`${process.env.BOT_TOKEN}`)
```

![photo_2022-08-13_12-38-37](https://user-images.githubusercontent.com/8447982/184508430-36d20366-a3bc-4135-9ac4-8b5d382d44bd.jpg)

Thanks.

**Comment by sartoshi-foot-dao** [comment]
Having the same issue. 1.9.2 works fine.

**Comment by roj1512** [comment]
Oh no

**Comment by roj1512** [comment]
Misclick.

**Comment by roj1512** [comment]
Anyways, is this Node.js or Deno?

**Comment by adnanlah** [comment]
> Anyways, is this Node.js or Deno?

Node.js.

**Comment by roj1512** [comment]
Have you tried upgrading the dependencies?

**Comment by adnanlah** [comment]
> Have you tried upgrading the dependencies?

Yes I did.
