### ISSUE TITLE
how to fix: chat_member update is not sent

### ISSUE THREAD

**Issue by mzoterov** [grammyjs/grammY#264]
_For developers who run into the same problem as me, here is the solution!_

If the chat_member update is not sent, run your bot with [all available update types](https://core.telegram.org/bots/api#update).
**If only chat_member is in allowed_updates, other events will be ignored!**

```ts
[
       `chat_member`,
       `edited_message`,
       `channel_post`,
       `edited_channel_post`,
       `inline_query`,
       `chosen_inline_result`,
       `callback_query`,
       `shipping_query`,
       `pre_checkout_query`,
       `poll`,
       `poll_answer`,
       `my_chat_member`,
       `chat_member`,
       `chat_join_request`,
       `message`
]

await bot.start({
     allowed_updates: [/*...*/],
});

// Or start with runner

run(bot, undefined, {
     allowed_updates: [/*...*/],
});
```

p.s. Thanks very much for solution: @Heero_T and @Loskir ([1](https://t.me/grammyjs/67620), [2](https://t.me/grammyjs/67315))

**Comment by KnorpelSenf** [comment]
This is already part of the documentation.
