### ISSUE TITLE
How to install Plugins?

### ISSUE THREAD

**Issue by bangjohn** [grammyjs/grammY#294]
how to install plugin?
i am new in node js

**Comment by bangjohn** [comment]
conversations plugin

can i use 2 plugins in the same time?

**Comment by KnorpelSenf** [comment]
Yes, you can use as many as you want

**Comment by KnorpelSenf** [comment]
Conversations plugin is still a bit new so sometimes it can be hard to combine it with some other plugins. This will be improved substantially in the coming time. Until then, you can ask questions here or [in the group chat](https://t.me/grammyjs) if you run into any problems :)

**Comment by KnorpelSenf** [comment]
Continuing as https://t.me/grammyjs/87335. Closing.
