### ISSUE TITLE
Is switch_inline_query or switch_inline_query_current_chat are usable with grammY

### ISSUE THREAD

**Issue by emmtte** [grammyjs/grammY#298]
Hi,

With inlinekeyboardbutton, I would like to use switch_inline_query or switch_inline_query_current_chat

https://core.telegram.org/bots/api#inlinekeyboardbutton

How to code this with Grammy ?

Not see in documentation

**Comment by KnorpelSenf** [comment]
This is how you can build inline keyboards: https://grammy.dev/plugins/keyboard.html#building-an-inline-keyboard

Here is the API reference of grammY which describes the relevant methods on the `inlineKeyboard` class: https://doc.deno.land/https://deno.land/x/grammy@v1.11.2/mod.ts/~/InlineKeyboard#Methods

This is how inline queries are handled with grammY: https://grammy.dev/guide/inline-queries.html

There is a seach bar on https://grammy.dev. It lets you find these places in the docs more easily. We also have a Telegram bot that can help you search the documentation (it uses the same search index): https://t.me/grammYdocsbot

I think this is covered well enough in the docs, so I will close this. Feel free to comment if you have further questions, though.
