### ISSUE TITLE
promisify(setTimeout)/conversation.sleep blocks bot to chat with other users

### ISSUE THREAD

**Issue by idel28102001** [grammyjs/grammY#305]
When I use sleep in conversation(or just promisify timeout to such function - it "blocks" chats with other users)

Like - If user ONE use that bot and bot goes to row with "SLEEP" function - for user TWO chat stops untill that sleep function resolves. Literally.

```
const bot = new Bot<MyContext>(process.env.TOKEN || '');
bot.use(
  session({
    initial: () => ({stage: 1}),
  })
);
const callback_data = 'hi';
const conver = 'conv';

bot.use(conversations());
bot.use(createConversation(async (conversation:MyConversation, context: MyContext)=>{
  await context.reply('Hi');
  await conversation.sleep(15*1000);
}, 
conver
));

bot.callbackQuery(callback_data, (ctx:MyContext)=> ctx.conversation.enter(conver));

bot.on('message', ctx =>ctx.reply('Here button', {reply_markup: {inline_keyboard: [[{text: 'Button', callback_data}]]}}));

bot.start();
```

There is "solution" - if I add that row before all code - nothing stops to chat with other users anymore
```
bot.use((ctx: MyContext, next) => {      
  next(); 
});
```

Wierd behave

**Comment by KnorpelSenf** [comment]
The whole point of that function is to block the execution of the middleware. This is what happens. If you don't want to do that, don't use this function.
