### ISSUE TITLE
bug: errors are not handled if run the bot using a webhook

### ISSUE THREAD

**Issue by mkeksz** [grammyjs/grammY#324]
I can't handle the error when running the bot with a webhook. 
The documentation says that the error will be passed to Express, but it is not passed.
And if I run the bot with long polling, the error will be caught in `bot.catch()`

```javascript
import {Bot, webhookCallback} from 'grammy'
import express from 'express'
import config from '@config'
export const bot = new Bot(config.token)

bot.on('message:text', async ctx => {
  throw new Error('test')
  await ctx.reply(ctx.message.text)
})
bot.catch(error => {
  console.log('error')
})

const server = express()
server.use(express.json())

server.use(webhookCallback(bot, 'express'))
server.use((error, req, res, next) => {
  console.log('error!')
  return res.sendStatus(500)
})
server.listen(8443)

bot.api.setWebhook(config.webhook)
```

**Comment by KnorpelSenf** [comment]
Old versions of express are simply unable to handle rejecting promises. The webhook adapter works well with express 5 and up, but requires manual wrapping for older versions which pass errors to `next`. If you must still use express, then mapping promises back to callbacks is the type of problem you'll have to deal with.
