### ISSUE TITLE
Filter by document types

### ISSUE THREAD

**Issue by ak4zh** [grammyjs/grammY#334]
I am still trying to understand the grammy `filter.ts` to figure out how to handle the suggestion I am going to make.

Just putting it out there to know if you guys will be interested in adding more filter options like below or if it's out of scope for the project.

```
const DOCUMENT_KEYS = {
	'apk': {},
	'doc': {},
	'docx': {},
	'exe': {},
	'gif': {},
	'jpg': {},
	'pdf': {},
	'py': {},
	'svg': {},
	'txt': {},
	'tarz': {},
	'wav': {},
	'xml': {},
	'zip': {}
}

const STICKER_KEYS = {
	'animated': {},
	'static': {},
	'video': {},
	'premium': {}
}

// L2
const EDITABLE_MESSAGE_KEYS = {
	text: {},
	animation: {},
	audio: {},
	document: DOCUMENT_KEYS,
        ....
}

const COMMON_MESSAGE_KEYS = {
	...EDITABLE_MESSAGE_KEYS,
	sticker: STICKER_KEYS,
        ...
}
```

**Comment by KnorpelSenf** [comment]
Filter queries work based on property names, not values. Check out https://grammy.dev/guide/filter-queries.html#the-query-language. This means that when a filter query is evaluated for an update, all it does is to check whether certain keys exist in the update.

What you're suggesting is to let filter queries also inspect the valuee, check if they're strings, and check if the strings end with the L3 part.

- This is not consistent with what filter queries do (check the presence of values)
- You cannot reliably determine a file type by its file extension
- Doing this is the filter queries is not flexible enough. What if someone wants to check for a different extension that isn't supported by us? What if someone wants to check the whole file name or match it against a regular expression?

Filter queries are the wrong place to do file name checks.

Regarding the addition of more sticker keys, tits can well be done. Feel free to open a pull request :)
