### ISSUE TITLE
Just a thank you note !

### ISSUE THREAD

**Issue by mrwaks** [grammyjs/grammY#336]
Sincere thanks to you for bringing this beauty of framework into the world!

I had started with Telegraf, but being addicted to Typescript, I very quickly went crazy with their complicated and poorly organized typing...

Then I came across you, and my life changed for the design of a chatbot for a client, which turned out to be the easiest and above all a golden documentation!  I have never seen such documentation in my life, a 5 year old child would understand it perfectly

So, thank you, thank you and again thank you for bringing this beautiful project to life, and thank God that there are developers like you on earth 🔥❤️

**Comment by KnorpelSenf** [comment]
Thank you so much! That is very kind of you :)

I will close this now, even though it feels a bit wrong to do so :D
