### ISSUE TITLE
is there any file downloading limit ?

### ISSUE THREAD

**Issue by rsoorajs** [grammyjs/grammY#354]
is there any file downloading restriction if i use this framework ? like [20 MB in size](https://core.telegram.org/bots/faq#:~:text=Use%20the%20getFile%20method.%20Please%20note%20that%20this%20will%20only%20work%20with%20files%20of%20up%20to%2020%20MB%20in%20size.) ?

**Comment by KnorpelSenf** [comment]
The framework can work with files of any size. However, Telegram itself restricts file sizes. If you use the hosted Bot API server at `api.telegram.org`, the download limit is 20 MB. This is the same value for every framework that connects to the Bot API.
