### ISSUE TITLE
node simply ends process soon after trying to run my bot

### ISSUE THREAD

**Issue by amanape** [grammyjs/grammY#382]
Everything was working fine earlier today, I run `tsc` and then `node dist/bot.js` to run my bot. Then, after deleting `node_modules` and reinstalling the deps, node immediately ends the process after a second of starting without any error or warning.

```sh
yarn run dev
```

RESPONSE:
```sh
yarn run v1.22.19
$ tsc && node dist/bot.js
✨  Done in 1.28s.
```

The strangest thing of all is that the same behaviour persists even if I replace all the source code in my main `bot.ts` file with the most basic example
```ts
import { Bot } from "grammy";

const TOKEN = ""
const bot = new Bot(TOKEN);

// Reply to any message with "Hi there!".
bot.on("message", (ctx) => ctx.reply("Hi there!"));

bot.start();
```

**package.json**
```json
{
  "license": "MIT",
  "version": "0.2.0",
  "scripts": {
    "dev": "tsc && node dist/bot.js",
    "build": "tsc"
  },
  "devDependencies": {
    "typescript": "^4.9.5",
    "vite": "^4.1.4",
    "vitest": "^0.28.5"
  },
  "dependencies": {
    "@grammyjs/conversations": "^1.1.1",
    "@grammyjs/files": "^1.0.4",
    "@types/exceljs": "^1.3.0",
    "grammy": "^1.14.1"
  }
}
```

Could it be something related to my account or token itself? I tried generating new ones, and node just ended in 3 seconds instead of 1 second but only on the first time I run the command.

**Comment by amanape** [comment]
Running `DEBUG='*' node dist/bot.js` gives me 
```
  grammy:bot Initializing bot +0ms
  grammy:core Calling getMe +0ms
  grammy:bot I am BT11829Bot! +285ms
  grammy:core Calling deleteWebhook +285ms
```

**Comment by jjjj222** [comment]
I faced the same issue (v1.15.0).
Solved by using v1.14.1 instead.

**Comment by felixniemeyer** [comment]
I have the same issue regardless of whether I'm using nodemon or deno
```
[nodemon] clean exit - waiting for changes before restart
```

**Comment by esindger** [comment]
The problem is in this [line](https://github.com/grammyjs/grammY/blame/main/src/bot.ts#L380).

**Comment by KnorpelSenf** [comment]
Right, that was stupid. You found it, do you quickly wanna fix it?

**Comment by KnorpelSenf** [comment]
@all-contributors add @amanape for bug

**Comment by KnorpelSenf** [comment]
I'll take this then.
