### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'update_id') in grammy bot.js file when using webhooks

### ISSUE THREAD

**Issue by siddiquiaffan** [grammyjs/grammY#404]
I'm building a telegram bot using grammy in node.js, and I'm getting the following error: 
```TypeError: Cannot read properties of undefined (reading 'update_id')``` 
The error is being caused by line 182, column 43 in the "bot.js" file located in the "node_modules/grammy/out/" directory.

Here is the code that is causing the error: 
```js
debug(Processing update ${update.update_id});  // node_modules/grammy/out/bot.js:182
```

This error only occurs when I am using webhooks to receive updates from Telegram. When I use long polling, the bot runs without any errors.

I'm not sure what is causing this error or how to fix it. I've tried searching for solutions online, but I haven't been able to find anything helpful. I would really appreciate any advice or guidance on how to resolve this issue.

### Steps to Reproduce:

- Install grammy in a node.js project
- Set up a telegram bot using grammy with webhooks enabled
- Run the bot and observe the error message

### Expected Result:
The bot should run without any errors, even when using webhooks to receive updates.

### Actual Results:

The error "TypeError: Cannot read properties of undefined (reading 'update_id')" is thrown when using webhooks to receive updates.

### Versions:
- Node.js: 18.12.1
- Grammy: 1.15.3

**Comment by KnorpelSenf** [comment]
You're using the wrong webhook adapter. See https://grammy.dev/guide/deployment-types.html#web-framework-adapters

**Comment by siddiquiaffan** [comment]
> You're using the wrong webhook adapter. See https://grammy.dev/guide/deployment-types.html#web-framework-adapters

I'm using express to create server and to listen routes.

What I did is
```js
import express from 'express'
import bot from './bot'

const app = express()

app.use('/bot', webhookCallback(my_bot_instance, 'express'))

app.listen(process.env.PORT || 8080)

**Comment by siddiquiaffan** [comment]
Sorry, My bad.

I forgot to use ```express.json()```.

Updated code (That works!):

```js
import express from 'express'
import bot from './bot'

const app = express()
app.use(express.json())

app.use('/bot', webhookCallback(bot, 'express'))

app.listen(process.env.PORT || 8080)
```
