### ISSUE TITLE
NextJS framework secret_token header key should be lowercase

### ISSUE THREAD

**Issue by inji-gg** [grammyjs/grammY#406]
I am trying to setup a bot using webhooks on NextJS/Vercel. When using a secret_token, the webhook callback fails with unauthorized. On inspecting the header, the secret_token header key should be lowercase.

<img width="510" alt="image" src="https://user-images.githubusercontent.com/5071242/232360174-b123cd23-ffe6-4bea-94a8-c6229265fe9c.png">

Would be great if you can make this change. Otherwise, if you grant me write permissions, I can create a PR as well

**Comment by KnorpelSenf** [comment]
I'd be happy to review a pull request. You can open it from your fork if this repo :)
Thanks!

**Comment by KnorpelSenf** [comment]
@all-contributors add @inji-gg for bug

**Comment by KnorpelSenf** [comment]
Fixed in #418.
