### ISSUE TITLE
deleteMessage throws an uncaught error (grammy  v1.16.0)

### ISSUE THREAD

**Issue by sobakieko** [grammyjs/grammY#431]
```
./node_modules/grammy/out/core/error.js:35
    return new GrammyError(`Call to '${method}' failed!`, err, method, payload);
           ^
GrammyError: Call to 'deleteMessage' failed! (400: Bad Request: message to delete not found)
    at toGrammyError (./node_modules/grammy/out/core/error.js:35:12)
    at ApiClient.callApi (./node_modules/grammy/out/core/client.js:86:48)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  method: 'deleteMessage',
  payload: { chat_id: -[ID], message_id: 1745798 },
  ok: false,
  error_code: 400,
  description: 'Bad Request: message to delete not found',
  parameters: {}
}
```

**Comment by KnorpelSenf** [comment]
This happens because you try to delete a message that does not exist. Telegram returns an error, and grammY throws it. You need to await all promises in your code and install an error handler on your bot: https://grammy.dev/guide/errors.html

**Comment by sobakieko** [comment]
> This happens because you try to delete a message that does not exist. Telegram returns an error, and grammY throws it. You need to await all promises in your code and install an error handler on your bot: https://grammy.dev/guide/errors.html

Well, that's the thing - I do have an error handler and it does indeed catch other (internal grammy) errors successfully, but this one gets thrown

**Comment by KnorpelSenf** [comment]
Do you ever call `next` without `await`?

**Comment by sobakieko** [comment]
> Do you ever call `next` without `await`?

nope, I don't use next at all

**Comment by KnorpelSenf** [comment]
You are not using await at all. If you start using async/await correctly, error handling will work as expected.

**Comment by KnorpelSenf** [comment]
`await ctx.api.deleteMessage(ctx.message.chat.id, 1000)` in case it wasn't clear what I meant

**Comment by sobakieko** [comment]
> `await ctx.api.deleteMessage(ctx.message.chat.id, 1000)` in case it wasn't clear what I meant

`const { Bot, Context } = require("grammy")
    , bot = new Bot(process.env.TOKEN)

async function del(ctx) {
  await ctx.api.deleteMessage(ctx.message.chat.id, 1000)
}

bot.on("message", ctx => {
  console.log("got context",ctx.message.chat.id,ctx.message.message_id)
  del(ctx)
})

bot.catch( err => console.log("caught error:", err.error) )

bot.start()`

produces exact same error. 
node v16.15.0

**Comment by dcdunkan** [comment]
This isn't a platform-specific issue. You still just doesn't await all calls. 

> async function del(ctx) {
>   await ctx.api.deleteMessage(ctx.message.chat.id, 1000)
> }
> 
> bot.on("message", ctx => {
>   console.log("got context",ctx.message.chat.id,ctx.message.message_id)
>   del(ctx)
> })
> ```

Here, you are wrapping the await-ed `deleteMessage` call in an async function, `del`. That's unnecessary, but that's not the issue. But in the message handler, you are not await-ing that `del` function. It is an async function, so, it **must** be await-ed if you don't want this error to occur.

If you are trouble with making the handler async, just take a look at _literally_ every single code snippet in the documentation at https://grammy.dev. It's like this in-case if you still can't find out how:

```js
bot.on("message", async (ctx) => {
  // ...
  await del(ctx); // or,
  await ctx.api.deleteMessage(/* ... */);
});
```

**Comment by sobakieko** [comment]
Thank you that resolves the issue.

Sure enough I didn't check all the snippets as not all apply in my use case, I was going off `bot.on("message"` snippets, where .on() is not qualified as async
