### ISSUE TITLE
"exports is not defined" With Next.js edge runtime functions 

### ISSUE THREAD

**Issue by va3y** [grammyjs/grammY#435]
Hi there, 

I'm using Next.js api, with an edge runtime. When I set up an API handler like this:
```typescript
// pages/api/bot.ts
import { Bot } from "grammy/web";
import { NextResponse } from "next/server";

export const runtime = "edge";

export default async function handler() {
	new Bot("<token>");

	return new NextResponse("Success", { status: 200 });
}
```

When accessing the route, I get this server error:
```
ReferenceError: exports is not defined

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
<unknown>
webpack-internal:///(middleware)/./node_modules/grammy/out/web.mjs (4)
eval
webpack-internal:///(middleware)/./node_modules/grammy/out/web.mjs (4:23)
```

This is related how cjs modules are exported and how it works with edge. Maybe it has to do with swc bundling.

Repo with the error reproduction: https://github.com/va3y/grammy-next-edge

**Comment by va3y** [comment]
Create a next.js issue as well. But my guess is that it can be fixable on the library side as well. If there is a way to access `module.exports`, instead of `exports`

**Comment by KnorpelSenf** [comment]
Can you describe the steps that are necessary to reproduce this problem based on the repo?

Alternatively, can you explain what the service expects of the module and what grammY does, i.e. what we need to change in order to fix this?

**Comment by va3y** [comment]
My bad, please repull main branch. I've forgot to push fully.  

How to get error: 
1. Branch main, run `npm run dev`
2. Access `http://localhost:3000/api/bot`

**Comment by va3y** [comment]
I've noticed that on next edge runtime, they don't have `exports` variable accessible as global. 
```
import { NextResponse } from "next/server";

export const runtime = "edge";

export default async function handler() {
	console.log(module); // OK
	console.log(module.exports); // OK

	console.log(exports); // ReferenceError: exports is not defined
}
``` 
My guess is that code may access it from the `grammy/web` somehow. Might be the bundler. I'll try to dig deeper, but I'm not that knowledgable about Deno bundling.

**Comment by KnorpelSenf** [comment]
It's an ES module. You can just look at the code inside. It uses `export { Bot as Not }` syntax.

**Comment by KnorpelSenf** [comment]
Is this fixed?

**Comment by va3y** [comment]
No, still there unfortunately. Right now I duck-taped it with manually importing the bundled .mjs file with 'exports' removed

**Comment by KnorpelSenf** [comment]
@PonomareVlad is this the type of challenge you would like to tackle? 🤓

**Comment by PonomareVlad** [comment]
@KnorpelSenf I drowned in urgent tasks, I really want to get back to work on grammY, but in the coming days (or weeks) I doubt that I will be free 🥲

**Comment by KnorpelSenf** [comment]
Hehe alright, good luck with the other stuff :D

This issue is currently tracked at https://github.com/vercel/next.js/issues/51313, as well. I think that the people there know a lot more about how their runtime works. You'll need to provide a complete reproduction example for them. I will close this issue in favour of the other one.

If you end up finding out that grammY is broken and your setup is correct, and we thus have to adjust something in grammY, please open a new issue. The comment at https://github.com/vercel/next.js/issues/51313#issuecomment-1594888767 seems to imply that the web build grammY is correct, so I don't yet see what we would have to do here.

**Comment by maccman** [comment]
Is this issue completed? I'm still seeing the error.

**Comment by maccman** [comment]
Here is a basic reproduction. https://github.com/maccman/grammyjs-nextjs-edge-bug

**Comment by PonomareVlad** [comment]
[I have working TypeScript example for Edge Runtime](https://github.com/PonomareVlad/grammY-Test/tree/vercel-edge-ts) using /api functions

@maccman How this is different from your setup ?

**Comment by maccman** [comment]
My guess is that something is up with the package.json configuration. I found it's quite a dark art to get it working, but for example I suspect you're missing some exports or typesVersions.

```json
  "main": "./dist/reflect-editor.js",
  "module": "./dist/reflect-editor.js",
  "types": "./dist/reflect-editor.d.ts",
  "exports": {
    ".": {
      "types": "./dist/reflect-editor.d.ts",
      "import": "./dist/reflect-editor.js",
      "default": "./dist/reflect-editor.js"
    },
    "./lite": {
      "types": "./dist/reflect-editor-lite.d.ts",
      "import": "./dist/reflect-editor-lite.js",
      "default": "./dist/reflect-editor-lite.js"
    },
    "./reflect-editor-static": {
      "types": "./dist/reflect-editor-static.d.ts",
      "import": "./dist/reflect-editor-static.js",
      "default": "./dist/reflect-editor-static.js"
    },
    "./dist/styles.css": {
      "default": "./dist/styles.css"
    }
  },
  "typesVersions": {
    "*": {
      "lite": [
        "dist/reflect-editor-lite.d.ts"
      ],
      "reflect-editor-static": [
        "dist/reflect-editor-static.d.ts"
      ]
    }
  },
```

**Comment by KnorpelSenf** [comment]
> Is this issue completed? I'm still seeing the error.

No. Did you read [my last comment](https://github.com/grammyjs/grammY/issues/435#issuecomment-1712844323)?

**Comment by PonomareVlad** [comment]
@va3y and @maccman can you test Edge build using #501 ?

```json
{
    "dependencies": {
        "grammy": "npm:@ponomarevlad/grammy@1.19.2-next-edge"
    }
}
```

Also you can check [this template](https://github.com/grammyjs/examples/pull/40) for **Next.js** using `/app` directory

**Comment by PonomareVlad** [comment]
@abigpotostew and, what about [this example](https://github.com/grammyjs/examples/tree/main/setups/next-node) ?

**Comment by abigpotostew** [comment]
> @abigpotostew and, what about [this example](https://github.com/grammyjs/examples/tree/main/setups/next-node) ?

This example does not work for me with the latest version of grammy 1.22.4. It does work with your branch `npm:@ponomarevlad/grammy@1.19.2-next-edge`.
