### ISSUE TITLE
Deno Deploy pricing doubled to $20/mo

### ISSUE THREAD

**Issue by CetinSert** [grammyjs/grammY#444]
https://grammy.dev/hosting/comparison.html#serverless-and-paas ← still lists them at $10/mo

**Comment by KnorpelSenf** [comment]
Oof … could you open a pull request to fix this? There is an edit button at the bottom of the page you linked.

**Comment by CetinSert** [comment]
https://github.com/grammyjs/website/pull/825

**Comment by CetinSert** [comment]
@KnorpelSenf – I just have ↖️
