### ISSUE TITLE
Is it possible to have an .on(callback_msg) ?

### ISSUE THREAD

**Issue by raskyer** [grammyjs/grammY#458]
I can't see in docs or examples how to filter on callback message data ? 

Such as : 
`bot.action(/regex/g, async (ctx) => {`
in telegraf.

Is it possible or not yet ?

**Comment by KnorpelSenf** [comment]
Of course this is possible. We support 100 % of the Bot API. See this: https://grammy.dev/plugins/keyboard.html#responding-to-clicks
