### ISSUE TITLE
Express deprecated use webhook

### ISSUE THREAD

**Issue by batdaucode** [grammyjs/grammY#463]
Hi there,

I'm using grammY with webhook (expressjs). I get 'express deprecated res.send(status, body): Use res.status(status).send(body) instead node_modules/grammy/out/convenience/frameworks.js:26:13' message when I enter the wrong secretToken. This is a warning not an error, but is it possible to fix it?

Thank you.

**Comment by KnorpelSenf** [comment]
Which versions are you using?

**Comment by batdaucode** [comment]
@KnorpelSenf "grammy": "^1.17.1"

**Comment by KnorpelSenf** [comment]
What version of express are you using?

**Comment by batdaucode** [comment]
express: v4.18.2

**Comment by KnorpelSenf** [comment]
I see. @PonomareVlad could you open a pull request to fix it?

**Comment by KnorpelSenf** [comment]
Or @batdaucode do you want to fix it yourself? It's not a difficult change :)

**Comment by PonomareVlad** [comment]
@KnorpelSenf Yes, I can do it in a couple of hours
