### ISSUE TITLE
Excess dependencies

### ISSUE THREAD

**Issue by sergeysolovev** [grammyjs/grammY#481]
In `types.deno.ts` there an import of the entire `path` module which causes unnesessary deps in deno.lock:

```
import { basename } from "https://deno.land/std@0.198.0/path/mod.ts";
```
It would probably be better to import from `https://deno.land/std@0.198.0/path/basename.ts`

**Comment by KnorpelSenf** [comment]
Huh, that's a good idea actually. Could you review https://github.com/grammyjs/grammY/pull/482?

**Comment by sergeysolovev** [comment]
@KnorpelSenf Thanks a lot! Left a review, lgtm
