### ISSUE TITLE
feat: implement static method for removing custom keyboard Keyboard.remove()?

### ISSUE THREAD

**Issue by gomez-git** [grammyjs/grammY#486]
I can't find quick way to remove keyboard, when reply to user, does grammy have static method or so to quickly implement this object: `{ remove_keyboard: true }` and use it like `{ reply_markup: Keyboard.remove() }`?

https://core.telegram.org/bots/api#replykeyboardremove

**Comment by gomez-git** [comment]
@KnorpelSenf 

Can you add an example using secret_token and ngrok? I spent too much time trying to get it to work.

**Comment by KnorpelSenf** [comment]
I don't think a few saved characters justify an inconsistency like this. It may be intuitive if you don't know the Bot API, but it's pretty confusing if you do know it, and I'm slightly in favour of not introducing it. Thanks for the suggestion, though!
