### ISSUE TITLE
Is it possible to wait for the conversation to end?

### ISSUE THREAD

**Issue by snurfer0** [grammyjs/grammY#489]
I am entering into a conversation inside a function, and even if I await the enter conversation function it does not wait for it to end.

```js
                do: async (ctx) => {
                    await ctx.conversation.enter(REGISTER_CALLER_ACTION.ADD_USERNAME);
                    console.log('should log after the conversation has finished'); // its logging before
                    return true;
                },
```

**Comment by KnorpelSenf** [comment]
No. Conversations can live for days until they complete, and there may be server restarts in between. This cannot work.
