### ISSUE TITLE
BUTTON_TYPE_INVALID error with InlineKeyboard().webApp

### ISSUE THREAD

**Issue by gut4** [grammyjs/grammY#490]
I try:
 ```
bot.on('channel_post', async (ctx) => {
     await ctx.editMessageReplyMarkup({
      reply_markup: new InlineKeyboard().webApp('app', url)
    })
})
```
 and get an error:
```
GrammyError in middleware: Call to 'editMessageRep…' failed! (400: Bad Request: BUTTON_TYPE_INVALID)
```

but this works fine:
 ```
bot.on('channel_post', async (ctx) => {
     await ctx.editMessageReplyMarkup({
      reply_markup: new InlineKeyboard().text('btn', 'btn1')
    })
})
```

**Comment by roj1512** [comment]
Does your bot have a web app?

**Comment by gut4** [comment]
> Does your bot have a web app?

yes

**Comment by roj1512** [comment]
Unfortunately, it seems like web app buttons are only available in private chats, and you’re trying to add them in a channel.

![image](https://github.com/grammyjs/grammY/assets/49933115/296f5007-df75-4d92-89ef-98ddb760e861)

**Comment by roj1512** [comment]
Meanwhile, you could try adding a URL button that includes the t.me link to your web app (e.g., t.me/yourbot/webappx).

**Comment by roj1512** [comment]
That’s exactly what I meant.
