### ISSUE TITLE
Is it possible to create a single logic for multi-tenant bot?

### ISSUE THREAD

**Issue by thecoorum** [grammyjs/grammY#502]
I want to create a single back-end that will be responsible for different bots using NextJS, but because we always need to initialize the bot with bot token before using it I can't fetch the bot token from any back-end before doing so. The question is is it possible at all and does anybody did this before?

**Comment by KnorpelSenf** [comment]
You can create a bot per request.

You may want to install all your middleware on a composer and then reuse this composer for every bot.

You may also want to set the `botInfo` when constructing your bot. This will skip the initialisation step.

**Comment by thecoorum** [comment]
@KnorpelSenf are there any docs or examples for something like this?

**Comment by thecoorum** [comment]
I'm also asking because of the specifics of configuration of API endpoint in NextJS where we need to do something like this to make it work

```
export const POST = webhookCallback(bot, "std/http");
```

and as far as I understood from another issue, something like the following is not working

```
export const POST = () => {
  return webhookCallback(bot, "std/http");
}
```

**Comment by thecoorum** [comment]
Okay, I was able to implement the behavior I wanted with the suggestions you provided. Here is the example code for anybody who's going to do something like that in the future

```js
export const POST = async (
  req: NextRequest,
  ...args: any[]
) => {
  const token = /* get your token */

  const bot = new Bot(token);

  bot.use(/* middlewares */);

  const handleUpdate = webhookCallback(bot, "std/http");

  return handleUpdate(req, ...args);
};
```

**Comment by KnorpelSenf** [comment]
> @KnorpelSenf are there any docs or examples for something like this?

There are a bunch of people and projects that do this, but I don't recall the name of any of them off the top of my head. You can search the group chat for them.

> I'm also asking because of the specifics of configuration of API endpoint in NextJS where we need to do something like this to make it work
> 
> ```
> export const POST = webhookCallback(bot, "std/http");
> ```
> 
> and as far as I understood from another issue, something like the following is not working
> 
> ```
> export const POST = () => {
>   return webhookCallback(bot, "std/http");
> }
> ```

webhookCallback creates a function that needs to be invoked with the right arguments. If you export `() =>` then there's no way for the bot to receive any data.

You can abstract a lambda over the function returned from webhookCallback, but you obviously need to pass the right arguments to it.
