### ISSUE TITLE
Error wasn't caught: GrammyError: Call to 'getUpdates' failed!

### ISSUE THREAD

**Issue by vsly-ru** [grammyjs/grammY#503]
While starting, grammy throws an error without catching/handling it:
```js
/app/node_modules/grammy/out/core/error.js:35
    return new GrammyError(`Call to '${method}' failed!`, err, method, payload);
           ^
GrammyError: Call to 'getUpdates' failed! (409: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running)
    at toGrammyError (/app/node_modules/grammy/out/core/error.js:35:12)
    at ApiClient.callApi (/app/node_modules/grammy/out/core/client.js:86:48)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Bot.fetchUpdates (/app/node_modules/grammy/out/bot.js:361:27)
    at async Bot.loop (/app/node_modules/grammy/out/bot.js:336:29)
    at async Bot.start (/app/node_modules/grammy/out/bot.js:275:9) {
  method: 'getUpdates',
```
The problem is not in the error, but in the fact that it did not handle it and thus it crashed the app.

My code:
```ts
  async startBot(token: string): Promise<void> {
    this.logger(`starting with token: "${token}"`);
    if (isNullOrEmpty(token)) return;
    this.bot = new Bot(token);
    this.bot.catch((error) => { // <- I expect it to catch errors here, according to the documentation
      this.error(error, "catch");
    });

    // ... command handlers

    this.bot.start();
    this.logger(`started`);
}
```

Grammy version: `"grammy": "^1.16.2"`
Node version: `v20.5.1`

If this problem has been fixed in a later version of Grammy, please let me know and I will close this issue. Thank you.

**Comment by KnorpelSenf** [comment]
It is the intended behaviour that the app crashes. Anything else would be wrong. The problem is on your side: https://grammy.dev/resources/faq#_409-conflict-terminated-by-other-getupdates-request

**Comment by vsly-ru** [comment]
@KnorpelSenf in this case, please update the documentation [page about error handling](https://grammy.dev/guide/errors).
Please add the information that you need to catch errors on start if you don't want an error to crash your application. 

In my case, crashing my app was wrong as I use grammy for important notifications in my project. My app doesn't consist of just a telegram bot.

**Comment by vsly-ru** [comment]
Okay, if you closed the issue without waiting for my reply(which seems rude), I'll open another one.

**Comment by KnorpelSenf** [comment]
I'm sorry, it wasn't my intention to be rude. It seemed like a straightforward question, I didn't expect that there was anything to be done here :)
