### ISSUE TITLE
Type Error when accessing chat_shared

### ISSUE THREAD

**Issue by Nabil-249** [grammyjs/grammY#505]
Wherever in my project I try to access the chat_shared property inside ':chat_shared' listener I get the type error:
**Property 'chat_shared' does not exist on type 'Message'**

Here's the simplest replication of getting the error:

```
import { Bot } from "grammy";

const bot = new Bot("");

bot.on(':chat_shared', async (ctx, next) => {

    // Error: Property 'chat_shared' does not exist on type 'Message'.ts(2339)
    const request_id = ctx.msg.chat_shared.request_id;
    console.log(request_id);
})

bot.start();
```

And if it matters, here's my compiler options:
```
{
  "compilerOptions": {
      "module": "NodeNext",
      "moduleResolution": "NodeNext",
      "target": "ES2020",
      "sourceMap": true,
      "outDir": "dist",
      "esModuleInterop": true,
      "allowSyntheticDefaultImports": true,
      "strict": true,
      "skipLibCheck": true,
      "noImplicitAny": true,
      "noUnusedLocals": true,
      "noUnusedParameters": true
  },
  "include": ["src/**/*"]
}
```

**Comment by Nabil-249** [comment]
Ok I found where the problem was. I accidentally renamed the property chat_shared to user_shared across all of my workstations.

The solution I did was to revert the name manually inside `@grammyjs/types/message.d.ts`.
Is there a method to do it via the terminal? I've tried `npm i` but it doesn't seem to work with me.

**Comment by KnorpelSenf** [comment]
You can nuke your node_modules and reinstall them.
```sh
rm -rf node_modules/ && npm install
```
