### ISSUE TITLE
Messagens sent from bot isn't accessible trough bot.on(":text"...

### ISSUE THREAD

**Issue by JeffersonTeixeira** [grammyjs/grammY#511]
I would like to reuse some complex methods which depends from Context Object.
The bot works in a supergroup, I though about sent a message to chat from bot.api.sendMessage(XXX) method and then catch the just message sent from bot.on(":text"...) but I was unable to. I also tried from promise in .then but it doesn't have the Context.

`bot.api.sendMessage("XXXX", "Teste").then(NO_CONTEXT_HERE => {
            this.myActionTeste(ctx?????, someParams)
        });`

**Comment by KnorpelSenf** [comment]
Context objects are wrappers around updates. Your bot doesn't receive updates when sending messages. You cannot use context objects here.

Instead,

1. Extract your complex functions from the context object to the top-level, and add parameters for the things you need from the context object (probably ` `ctx.msg` and `ctx.api` or something)
2. Install a shortcut on the context object that calls the new functions with the required parameters, these shortcuts replace what was installed on the context object previously
3. Obtain the sent message object

```ts
const message = await bot.api.sendMessage(..)
message.text // etc
```

4. Get the relevant data from the message object
5. Call the new functions that no longer depend on the context object with parameters like `message`, `bot.api`, and so on

**Comment by JeffersonTeixeira** [comment]
What about bot receive the message sent by itself at bot.on(":text"...) ?

**Comment by KnorpelSenf** [comment]
> Context objects are wrappers around updates. Your bot doesn't receive updates when sending messages. You cannot use context objects here.

This is still valid.
