### ISSUE TITLE
Why is this version incompatible with @grammyjs/types@3.3.0? 

### ISSUE THREAD

**Issue by Kinghood15** [grammyjs/grammY#512]
Hello, I am unable to build due to a conflict with the @grammyjs/types library. Your library only uses @grammyjs/types@2.12, while Grammy itself uses @grammyjs/types@3.3.0. When I program on my computer everything is fine, but when I try to build I get a library version conflict error.

Specifically, I am using your library which depends on @grammyjs/types@2.12, but Grammy requires @grammyjs/types@3.3.0. So when I build, it tries to install both versions at the same time and fails.

This is likely happening because your library has not yet been updated to support the latest version of @grammyjs/types. Library dependencies can be tricky when version ranges do not overlap.

Do you have any suggestions on how I can resolve this situation? I need to build my project but cannot have conflicting versions of @grammyjs/types installed simultaneously. Please advise if there is a workaround or if I should wait for your library to release a new version supporting @grammyjs/types@3.3.0. Thank you!

**Comment by KnorpelSenf** [comment]
Which library are you talking about? This repository contains grammY itself. There is not much we can do.
