### ISSUE TITLE
send image Buffer error

### ISSUE THREAD

**Issue by johnnguyen-nodejs** [grammyjs/grammY#523]
`
const address = "0x235fF667f9F4eC9F84d886Bd4e9361d0409b0CC0"
const url = await QRCode.toBuffer(`ethereum:${address}?value=${rd(Number(0.1)*1e18, 0)}`, { width: 400})
await ctx.replyWithPhoto(url, { caption: `👋 Hi, ${ctx.from.first_name}! \n\n🌟 Deposit To Upgrade: \n\n💳 Address: <code>VGpLHmTqkGxcwkVzVypAUpyxccCqexiPgtmjQJWirSy</code>\n🔸Chain: BSC\n💰 Amount: <code>0.1</code> BNB`, parse_mode: 'HTML'})
`

Not working, please help

**Comment by KnorpelSenf** [comment]
Please start reading documentation: https://grammy.dev/guide/files#uploading-raw-binary-data
