### ISSUE TITLE
Missing type declaration: `has_hidden_members` is missing in type `ChatFromGetChat`.

### ISSUE THREAD

**Issue by erenertas** [grammyjs/grammY#533]
```typescript
// In .../node_modules/@grammyjs/types/manage.d.ts - Consider line 182
/** This object represents a chat. */
export type Chat = Chat.PrivateChat | Chat.GroupChat | Chat.SupergroupChat | Chat.ChannelChat;
/** This object represents a Telegram user or bot that was returned by `getChat`. */
export type ChatFromGetChat = Chat.PrivateGetChat | Chat.GroupGetChat | Chat.SupergroupGetChat | Chat.ChannelGetChat;
/** This object represent a user's profile pictures. */
export interface UserProfilePhotos {
``` 

ChatFromGetChat type should give me the has_hidden_members but couldn't

> _From [Official Telegram API Reference](https://core.telegram.org/bots/api#chat)_
> | Field | Type | Description |
> |--------|--------|--------|
> | has_hidden_members | True | _Optional_. _True_, if non-administrators can only get the list of bots and administrators in the chat. Returned only in [getChat](https://core.telegram.org/bots/api#getchat). |

**Comment by KnorpelSenf** [comment]
Please review #571
