### ISSUE TITLE
@ChatType does not work

### ISSUE THREAD

**Issue by Ice-Hazymoon** [grammyjs/grammY#546]
https://github.com/grammyjs/nestjs/blob/366c0108e7be2ea37e7b33f8c18a6f6132258b91/apps/sample-echo-bot/src/app/bot/bot.update.ts#L94

I try to run sample-echo-bot and I get the same problem

![image](https://github.com/grammyjs/grammY/assets/25239977/059c18f5-e889-4f49-9413-703c77e58a29)

**Comment by Ice-Hazymoon** [comment]
Sorry, I got the wrong repository, it should be [grammyjs/nestjs](https://github.com/grammyjs/nestjs)

**Comment by roj1512** [comment]
We could have transferred it, but alright!
