### ISSUE TITLE
Update to oak new `request.body` API

### ISSUE THREAD

**Issue by gabelluardo** [grammyjs/grammY#547]
When I try to use oak on Deno Deploy I have this error message at runtime 

![immagine](https://github.com/grammyjs/grammY/assets/42920247/5cb377e3-db5e-4038-8e73-2ba728943598)

seems like an incompatibility issue with the new API https://github.com/oakserver/oak/issues/634

**Comment by KnorpelSenf** [comment]
That sounds reasonable. Could you open a pull request to fix it? :)

**Comment by gabelluardo** [comment]
Yeah, sure, can you give me a hint of what these functions do, so I know how to modify it?

https://github.com/grammyjs/grammY/blob/c79df4a63c2693535f427481995a9be46c03af07/src/convenience/frameworks.ts#L277-L290

**Comment by KnorpelSenf** [comment]
Absolutely. Those functions make up the interface between grammY and each web framework. They define how to obtain the update object from the Bot API's webhook request, and provide several ways to respond to the webhook request.

[Here](https://github.com/grammyjs/grammY/blob/c79df4a63c2693535f427481995a9be46c03af07/src/convenience/frameworks.ts#L29) is the definition of the interface with documentation for every field. Also, you will find numerous examples in the same file, illustrating how to use them.

**Comment by KnorpelSenf** [comment]
You may also find https://github.com/grammyjs/grammY/blob/main/CONTRIBUTING.md#coding useful
