### ISSUE TITLE
baseApiUrl not working

### ISSUE THREAD

**Issue by ningtt** [grammyjs/grammY#558]
code
`
const { Bot, InputFile } = require("grammy");
const fs = require("fs");

const bot = new Bot("xxxxxx:xxxxx", {
  baseApiUrl: "http://1.2.3.4:1234",
});
`
I made sure that the server I built was running properly. But when I configured baseApiUrl, he didn't seem to recognize this parameter and make changes.

**Comment by KnorpelSenf** [comment]
That option simply does not exist. Why did you think it exists? https://grammy.dev/ref/core/botconfig
