### ISSUE TITLE
feat: ctx.message.message_thread_id presumably should not be | undefined in message:is_topic_message

### ISSUE THREAD

**Issue by mordv** [grammyjs/grammY#569]
I might be mistaken, or my IDE misleading me, but I think `message_thread_id` should not be undefined in this scenario.
<img width="1219" alt="Screenshot 2024-05-07 at 23 55 12" src="https://github.com/grammyjs/grammY/assets/32086218/10fa191e-94ca-473e-b06f-d7012079a27e">

Should it also infer correct type without specifying `chatType('supergroup')` explicitly, since is_topic_message is only available in supergroup?

**Comment by KnorpelSenf** [comment]
You're right.

These things don't happen automatically. Every such case has to be programmed manually. We can do this easily.

Note to self: We can define a same-level twin type on L2 for `is_topic_message: message_thread_id`.

**Comment by KnorpelSenf** [comment]
Simply needs to be added to https://github.com/grammyjs/grammY/blob/f1950b30d4d7bfd28f4d7521365ef10db3cb8899/src/filter.ts#L717

**Comment by KnorpelSenf** [comment]
While we're at it, we can make sure that caption entities ensure the existence of a caption

**Comment by KnorpelSenf** [comment]
@mordv I have implemented this in #573. Can you try out the changes and let me know if they work for you? If they do, please approve the pull request.

**Comment by KnorpelSenf** [comment]
@all-contributors add @mordv for this idea!
