### ISSUE TITLE
Add error type to `GrammyError`

### ISSUE THREAD

**Issue by taminomara** [grammyjs/grammY#589]
As I understand, telegram API returns [error type](https://core.telegram.org/method/messages.editMessage#possible-errors) on error. I'd like to have access to it so that I distinguish between expected and not expected errors. For example, I'd like to ignore `MESSAGE_NOT_MODIFIED` and throw anything else. Right now I have to check if error description contains some keywords, which is less reliable than checking error type.

**Comment by taminomara** [comment]
Oh no, it doesn't :(

**Comment by KnorpelSenf** [comment]
That's right, grammY already exposes everything there is :)
