### ISSUE TITLE
Allow using AbortController in globalThis if available

### ISSUE THREAD

**Issue by rojvv** [grammyjs/grammY#598]
Newer versions of Node.js have `AbortController` in `globalThis`, but it cannot be used since type errors are occurred conflicting with the one from `abort-controller`. Maybe we should allow them too?

https://github.com/grammyjs/grammY/blob/334f6179804ecb804f9ce8e9ebb3e1d1c4d34a82/src/shim.node.ts#L1

**Comment by KnorpelSenf** [comment]
Done for 2.0 in 01d633f0ce6e1f46371130e762445510639d722c
