### ISSUE TITLE
Didn't receive any messages

### ISSUE THREAD

**Issue by banx9x** [grammyjs/grammY#612]
I’m learning to create my own bot. I’m following a tutorial in the documentation, but I don’t understand why it isn’t working.

Here is my code:

```ts
import { config } from "dotenv";
import { Bot } from "grammy";

// Load environment variables
config();

const bot = new Bot(process.env.BOT_TOKEN);

// Commands
bot.command("start", async (ctx) => {
  ctx.reply("Welcome! Up and running.");
});

// Messages
bot.on("message", (ctx) => {
  console.log(ctx);

  ctx.reply("Hmm");
});

// Start the bot (using long polling)
bot.start();
```

After running the bot, nothing happens when I send a message to it.

<img width="377" alt="SCR-20240710-jevh" src="https://github.com/grammyjs/grammY/assets/72425188/ceea1889-aa7f-4237-9b04-f9a9b512085e">

**Comment by KnorpelSenf** [comment]
Set `DEBUG` and see what is logged.
```sh
export DEBUG='*'
```

**Comment by banx9x** [comment]
> Set `DEBUG` and see what is logged.
> 
> ```shell
> export DEBUG='*'
> ```

I discovered the error was due to Node version 21, I used version 18 and it worked. But strangely, no errors were printed, including the DEBUG set

**Comment by KnorpelSenf** [comment]
There is a bug in Node>18 that it can't perform network requests reliably if the ping is higher than 250 ms. Using Node 18 will work.
