### ISSUE TITLE
Error: Bot crashes once a message is sent

### ISSUE THREAD

**Issue by arewageek** [grammyjs/grammY#620]
Whenever a message is sent to the bot, it always throws an error in the console suggesting I'm registering more listeners in the bot.

Here's the error message it returns:

```shell
Error occurred while processing request 550 | but you did not specify them in \`allowed_updates\`
``` 

![image](https://github.com/user-attachments/assets/b965b6c7-7cfb-4b1b-8bf6-68de7d379108)
![image](https://github.com/user-attachments/assets/e5417e1e-bd41-4cd3-9ee1-0ab159866035)

Above is the complete error on my console

Here's the implementation I did in my code
![image](https://github.com/user-attachments/assets/cb0a5e5a-6318-4120-90af-144a989db568)
![image](https://github.com/user-attachments/assets/3d119512-b4cf-4333-9c7b-435d61c2b4b8)

I've tried checking for help online but failed to get any related to my problem. I will really appreciate it if I get a response real quick.

**Comment by KnorpelSenf** [comment]
The error message explains the problem very well. Here is what your code does:
- you first start your bot on long polling by calling `bot.start`
- you then add a request handler for the route `/bot`
- every time a request is received, you add a new start command handler to the bot via `bot.command("start")`

This means that if you handle 1000 requests, your bot will now have 1000 identical start commands handlers registered. That's not what you meant to do, and grammY detects this and throws an error. 

Note that your code:
- doesn't actually run on webhooks
- never receives any of the updates from your web server

You should probably take a second (first?) look at how to use webhooks. https://grammy.dev/guide/deployment-types#how-to-use-webhooks

**Comment by arewageek** [comment]
Thank you so much for that. Will read through the guide you sent. But I have one question pls. does this mean the bot start command is supposed to be written outside the route?

**Comment by KnorpelSenf** [comment]
> does this mean the bot start command is supposed to be written outside the route?

Yep, exactly! First set up your bot with all handlers, then turn it into a callback function using `webhookCallback`, then set up your routes which call this function.

**Comment by arewageek** [comment]
Thank you so much. I read about the concurrency with grammY runner docs and I got to understand it better. I migrated to the long polling instead. It's working perfectly now.
Thank you so much 😁

I would get back to learning about the webhook. As soon as I perfectly understand it I will get my hands working on it.

Thank you so much for your support. You're a real MVP
