### ISSUE TITLE
[Question] Does grammy works on edge runtime

### ISSUE THREAD

**Issue by abdulahd2008** [grammyjs/grammY#636]
Hello, I just recently stumbled upon this library, and want to know if it can run on serverless envorinment, does grammy support serverless/edge runtime ?

**Comment by KnorpelSenf** [comment]
Of course.

Check out https://grammy.dev/hosting/comparison#serverless-and-paas to see a comparison of serverless hosting solutions. Also, be sure to take a look at the hosting guides in the same section. Most of them describe how to host grammY in serverless environments.

**Comment by abdulahd2008** [comment]
That was quick!

Thanks! :heart:

**Comment by KnorpelSenf** [comment]
Very welcome! 🎉
