### ISSUE TITLE
bot.start() returning promise never resolves

### ISSUE THREAD

**Issue by atassis** [grammyjs/grammY#642]
I am starting a bot with `bot.start()` without setting any webhook. I also want to know that the start happened successfully with promise resolving of mentioned method. Instead, the Promise just "hangs" during long polling and you can receive a current state of the start only via bot `isInited()` method. Still, it doesn't provide a proper state, because nothing ever cleans `this.me` (including calling a `bot.stop()` method).
In most frameworks, and also in the standard http library, a created server instance resolves a promise, providing a batch of related data. It might be useful to return a botinfo and other related data in the `bot.start()` method. Furthermore, promises are meant to resolve in any way (to resolve or to reject).

**Comment by atassis** [comment]
Also it might be useful to track any issues for a server with a connection to tg servers. For example, if api is not responding- you could throw an error during `start` call.

**Comment by Viiprogrammer** [comment]
It's a feature, not a bug. Please read the documentation. 
https://grammy.dev/ref/core/bot#start

**Comment by KnorpelSenf** [comment]
> I am starting a bot with `bot.start()` without setting any webhook. I also want to know that the start happened successfully with promise resolving of mentioned method. Instead, the Promise just "hangs" during long polling and you can receive a current state of the start only via bot `isInited()` method. Still, it doesn't provide a proper state, because nothing ever cleans `this.me` (including calling a `bot.stop()` method). In most frameworks, and also in the standard http library, a created server instance resolves a promise, providing a batch of related data. It might be useful to return a botinfo and other related data in the `bot.start()` method. Furthermore, promises are meant to resolve in any way (to resolve or to reject).

This was a very early design mistake. The idea was to avoid floating promises entirely—`bot.start` resolves when the polling completes, and it rejects when the polling fails. This clearly is not intuitive, and it differs greatly from how everybody else does it. Sadly, fixing it would be a breaking change, so it cannot be changed before 2.0.

Until then, you can do the following workaround:

```ts
bot.start({ onStart: (botInfo) => { /* polling  is running now */ } })
  .then(() => { /* bot has stopped again */ }
  .catch((e) => { /* bot has stopped with error e */ })
```

> Also it might be useful to track any issues for a server with a connection to tg servers. For example, if api is not responding- you could throw an error during `start` call.

This is already implemented. The promise will reject correctly even before `onStart` is called.

**Comment by atassis** [comment]
Thanks for an extensive answer, @KnorpelSenf! It wasn't that obvious after a short read-throught of the docs (I have found @Viiprogrammer 's mentioned API, which (API) made no obvious sense). It might be nice to add this to the docs. I'll try to make a PR into the docs later for this. And about the breaking change- you don't have to be afraid to make one, it is ok until all versions are bumped properly.
Thanks again!

**Comment by KnorpelSenf** [comment]
Thanks, looking forward to the changes!

I'm not afraid of 2.0, I actually can't wait to get started. I just want to get version 2.0 of the conversations plugin done before that.

**Comment by KnorpelSenf** [comment]
This seems to be answered
