### ISSUE TITLE
 No types for parameter disable_web_page_preview

### ISSUE THREAD

**Issue by straystreyk** [grammyjs/grammY#643]
Hello! When using bot.api.sendMessage with the disable_web_page_preview: true parameter, the typescript says that there is no such parameter, although when it is sent, everything works correctly.

```
bot.api.sendMessage(user.dataValues.telegram_id, text, {
              parse_mode: "HTML",
              reply_markup: keyboard,
              // @ts-ignore
              disable_web_page_preview: true,
            })
            .catch((e) => {
              console.log(e.message);
            });
```

**Comment by KnorpelSenf** [comment]
Good. That means you're using an outdated version of the Bot API and grammY caught it. You should update your code to the latest version.

The option was renamed in the Bot API in December, and there was a news post about it: https://t.me/grammyjs_news/58
