### ISSUE TITLE
 How to deploy to vercel？

### ISSUE THREAD

**Issue by okssq** [grammyjs/grammY#647]
I followed the tutorial https://grammy.dev/zh/hosting/vercel, but why the robot cannot run.
The log records on vercel feedback the following 2 information

[POST] /api/bot status=500

TypeError: req.json is not a function
    at stdHttp (/var/task/node_modules/grammy/out/convenience/frameworks.js:254:21)
    at /var/task/node_modules/grammy/out/convenience/webhook.js:23:79
    at Server.<anonymous> (/opt/rust/nodejs.js:1:10660)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Server.<anonymous> (/opt/rust/nodejs.js:8:4429)
    
    
I'm very anxious. Can you help me?

**Comment by okssq** [comment]
i use CommonJS specification

**Comment by KnorpelSenf** [comment]
If you need help with a programming problem, you need to share the code you wrote.

Also, there are are several examples for vercel here: https://github.com/grammyjs/examples/tree/main/setups

**Comment by okssq** [comment]
> If you need help with a programming problem, you need to share the code you wrote.
> 
> Also, there are are several examples for vercel here: https://github.com/grammyjs/examples/tree/main/setups

3q
