### ISSUE TITLE
Simplify TypeScript Compilation and Execution Process in Documentation

### ISSUE THREAD

**Issue by suprunchuk** [grammyjs/grammY#649]
Hello grammY team,

I've noticed a potential area for improvement in the documentation regarding the process of compiling and running TypeScript bots.

Currently, the [Getting Started guide](https://grammy.dev/guide/getting-started) instructs users to compile the TypeScript code using `npx tsc` and then run the resulting JavaScript file with `node bot.js`. However, this two-step process can be simplified.

In the [official Telegram bot example](https://gitlab.com/Athamaxy/telegram-bot-tutorial/-/blob/main/Nodejs/package.json), a more streamlined approach is used:

```json:package.json
"scripts": {
  "start": "ts-node ./TutorialBot.ts",
  "dev": "ts-node-dev ./TutorialBot.ts",
}
```
Now you can easily run it through the command: `npm run dev`

**Comment by KnorpelSenf** [comment]
The goal of the getting started guide is not to reduce the number of commands that users must run. The goal is to use very few tools and make it as easy to understand as possible.

People who know how to set up TS will be able to change their setup in no time without even thinking about it. However, there are many people who don't even really know what TS means, and they blindly copy the commands from the website. It is important that they are able to understand what they have done as soon as possible. Adding more tools to this setup makes that process a lot more confusing.

So I don't think that our docs are the right place for these tools, but thanks for the suggestion anyway :)

**Comment by KnorpelSenf** [comment]
In fact, we should maybe just rank the Deno setup higher than the Node one. This order was picked years ago, but the Deno setup is so drastically more simple that we might want to change this.
