### ISSUE TITLE
After update with big extimol i.e. 1.31.1 cloudflare workers stopped working, I think it was because fetch was added to this ApiClientOptions.

### ISSUE THREAD

**Issue by KnorpelSenf** [grammyjs/grammY#659]
After update with big extimol i.e. 1.31.1 cloudflare workers stopped working, I think it was because fetch was added to this ApiClientOptions.

Error log in Cloidflare workers:
TypeError: Illegal invocation: function called with incorrect `this` reference.

<img width="1160" alt="image" src="https://github.com/user-attachments/assets/ff1b5192-e477-4fba-a8f2-7fe18a450435">

_Originally posted by @BilagoNet in https://github.com/grammyjs/grammY/issues/655#issuecomment-2466660778_

**Comment by KnorpelSenf** [comment]
@BilagoNet can you update to 1.31.2 and check if this issue was fixed?

**Comment by KnorpelSenf** [comment]
> @BilagoNet can you update to 1.31.2 and check if this issue was fixed?

@vorant94 can you do the same?

**Comment by BilagoNet** [comment]
yes, fixed

**Comment by vorant94** [comment]
confirming it on my end, thanks!

**Comment by KnorpelSenf** [comment]
Epic, thank you guys!

@all-contributors add @BilagoNet for bug and review

@all-contributors add @BilagoNet for review

**Comment by KnorpelSenf** [comment]
@all-contributors add @vorant94 for review, too
