### ISSUE TITLE
Cannot find name 'BodyInit'

### ISSUE THREAD

**Issue by LuiJunYe** [grammyjs/grammY#674]
Problem
- node_modules/.pnpm/grammy@1.33.0/node_modules/grammy/out/convenience/frameworks.d.ts:178:17

I have updated the grammy to latest version 1.33.0 but encounter error when build the middleware application using typescript.

Related  Library
- "grammy": "^1.33.0"
- "typescript": "5.7.2"
- "@types/node": "22.10.2"
-  "@types/node-fetch": "^2.6.12"
- "ts-node": "10.9.2"

**Comment by KnorpelSenf** [comment]
You may have to enable `skipLibCheck`.

Either way, the relevant code hasn't been updated in a long time. What grammY version did you use previously?

**Comment by LuiJunYe** [comment]
first time using grammY to build telegram mini app
