### ISSUE TITLE
feat: `File` support in `InputFile`

### ISSUE THREAD

**Issue by wojpawlik** [grammyjs/grammY#725]
Related: #675

Easy: `if (file instanceof File) return file.name` in `guessFilename()`.

Bonus: change

```ts
export class InputFile {
  public readonly filename?: string;
  async toRaw(): Promise<
    Uint8Array | Iterable<Uint8Array> | AsyncIterable<Uint8Array>
  >
}
```
to
```ts
export class InputFile {
  readonly name?: string;
  async stream(): AsyncIterable<Uint8Array>;
}
```

This would:
- align with web standards,
- simplify file handling in `Client`,
- increase flexibility: `new InputFile(inputFile, "new name")`,
- give us the option to add a `[Symbol.hasInstance]()` accepting `BunFile`, and `InputFile` from other grammY versions.

**Comment by KnorpelSenf** [comment]
@all-contributors add @wojpawlik for code
