### ISSUE TITLE
Incorrect message model

### ISSUE THREAD

**Issue by l1acy** [grammyjs/grammY#730]
I noticed that when forwarding a message, the bot cannot get 'forwand_origin' and 'forwand_from_chat', although they are in the telegram message object
![image](https://github.com/user-attachments/assets/3c456ea3-5ec5-470c-81d3-71d810cf3460)
![image](https://github.com/user-attachments/assets/8aedc741-c1c1-448a-b6e1-470d38267307)

* i use latest grammY version

**Comment by KnorpelSenf** [comment]
This works as expected. You have to check the chat type first. The type cannot be inferred from the target chat identifier so you must narrow it down.

**Comment by l1acy** [comment]
> This works as expected. You have to check the chat type first. The type cannot be inferred from the target chat identifier so you must narrow it down.

oh, sorry, my bad!

```ts
if (ctx.message?.forward_origin?.type != 'channel') return
```
